import { ActionType } from 'typesafe-actions';
import * as actions from './actions';

/* action type start */
export const ADD_PRODUCT_CATEGORY_REQUEST = 'products/ADD_PRODUCT_CATEGORY_REQUEST';
export const ADD_PRODUCT_CATEGORY_SUCCESS = 'products/ADD_PRODUCT_CATEGORY_SUCCESS';
export const ADD_PRODUCT_CATEGORY_FAILURE = 'products/ADD_PRODUCT_CATEGORY_FAILURE';

export const SHOW_PRODUCT_CATEGORY_REQUEST = 'products/SHOW_PRODUCT_CATEGORY_REQUEST';
export const SHOW_PRODUCT_CATEGORY_SUCCESS = 'products/SHOW_PRODUCT_CATEGORY_SUCCESS';
export const SHOW_PRODUCT_CATEGORY_FAILURE = 'products/SHOW_PRODUCT_CATEGORY_FAILURE';

export const DETAIL_PRODUCT_CATEGORY_REQUEST = 'products/DETAIL_PRODUCT_CATEGORY_REQUEST';
export const DETAIL_PRODUCT_CATEGORY_SUCCESS = 'products/DETAIL_PRODUCT_CATEGORY_SUCCESS';
export const DETAIL_PRODUCT_CATEGORY_FAILURE = 'products/DETAIL_PRODUCT_CATEGORY_FAILURE';

export const UPDATE_PRODUCT_CATEGORY_REQUEST = 'products/UPDATE_PRODUCT_CATEGORY_REQUEST';
export const UPDATE_PRODUCT_CATEGORY_SUCCESS = 'products/UPDATE_PRODUCT_CATEGORY_SUCCESS';
export const UPDATE_PRODUCT_CATEGORY_FAILURE = 'products/UPDATE_PRODUCT_CATEGORY_FAILURE';

export const PRODUCT_CATEGORY_RESET = 'products/PRODUCT_CATEGORY_RESET';

/* action type end */

export type AppAction = ActionType<typeof actions>;
